### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by zhouji0212** [annex4-inc/vscode-control4-ext#2]
When I Use VSCode Command Create Project It Show An Err: "command control4.create not found" And Other Command Also Show
command not found err

**Comment by zhouji0212** [comment]
i'm use vsce pack this program it's done!

**Comment by techguydave** [comment]
Can you explain exactly how you solved this?

**Comment by techguydave** [comment]
Nevermind, figured it out. Need to open an empty folder first, then run the Create Project command.
