### ISSUE TITLE
Hi, where did you find all these definitions?

### ISSUE THREAD

**Issue by michael-land** [annex4-inc/vscode-control4-ext#3]
I'm new to control4 driver development.

I wonder where did you find all these definitions. I cannot find these on their docs.

For example, where can i find a list of proxy types?

https://github.com/annex4-inc/vscode-control4-ext/blob/master/client/src/control4/C4Proxy.ts#L10-L30

Thank you!

**Comment by dinolink22** [comment]
I'm a new dev too! I finished developing a full IP driver recently :D 

I'm not sure if this, is gonna help but you can see proxies here:
https://snap-one.github.io/docs-driverworks-proxyprotocol/
the name suggests/tells you the proxies, then again you can also create your own proxy so it really depends what you trying to do...

Anyway if you only want to see the proper name of the proxy and want a full list, in driver editor, in the driver.xml in the proxy tab, if you try to add a new proxy you can see the whole list.
Here is the full list directly from Driver Editor :

![image](https://user-images.githubusercontent.com/91555793/174903186-b2d99e95-5035-4906-9d45-c20f124b1566.png)
![image](https://user-images.githubusercontent.com/91555793/174903211-d0af740f-0a35-4a95-a5e9-2a5b28da73dc.png)

Hope it helps!

**Comment by michael-land** [comment]
wow, thanks. I don't know there is an editor for that.
