### ISSUE TITLE
Combo Driver

### ISSUE THREAD

**Issue by AndrewBHarmon** [annex4-inc/vscode-control4-ext#4]
Does this plugin support the creation of combo drivers? I have not been able to get the combo tag included into the driver.xml file without manually including it after the build. I would love to know where I need to include this to get it built in if the plugin does support this. 
Thanks

**Comment by annex4** [comment]
If the filename matches the proxy it'll automatically be set. I could add an override to the logic in the package.json control4 section as well.

**Comment by annex4** [comment]
Added support for 'combo' in the control4 section of the packge.json file, see commit e9c4bbcd0a816088844babf77257077e327c00ca
